### ISSUE TITLE
Always visible edit map buttons

### ISSUE THREAD

**Issue by Renkineko** [emanchado/lyre#1]
If you have a map with a big height, you have to scroll down, make you change to publish, then scroll up to hit the publish button.

It could be a time saver to have the buttonset always visible in the map edit mode :)

Great project by the way. I'll probably use it (my next session is tomorrow so it's a little difficult to this one, but the next after this one i'll use it for sure, at least for map and music ^^)

**Comment by emanchado** [comment]
Hi, update your code, I made a simple fix for it (and you can have a look at the diff if you're curious).

I just realised I forgot to mention you, or this issue, in the commit and I already pushed. Sorry :-(

**Comment by Renkineko** [comment]
Nice reactivity :) no need to mention me (i don't see the point ^^).

I just gave it a try, it's perfect =] thanks a lot :)

**Comment by emanchado** [comment]
Well, it's nice to give credit for ideas and bug reports, not just code. I knew this was a problem, but I could have just let it be annoying, or do something horrible like try to implement zoom in and zoom out, or scale the whole map. So your idea might have "saved" the mapping UI :-)

Glad you like it :-) Do tell me how it goes when you try to use it "in production" :-)
